Properly validate postcodes with country code
osm-search/Nominatim pull request #3228
Opened 2023-10-16 23:15 UTC by pawel-wroniszewski

Include postcode pattern in postcode normalisation regex, instead of removing it from postcode pattern in config.

It properly handles postcode validation and normalization when country code is part of the postcode, e.g. for Isle of Man, Jersey, Anguilla, Andorra, Cayman Islands and more.

Fixes #3227.

2023-10-17 07:07 UTC, lonvia requested changes
The fix in postcode_format.py is okay.

Getting rid of the optional country codes is not acceptable. Both forms are used in these countries and there is no reason to reject one form or the other.

2023-10-17 09:28 UTC, pawel-wroniszewski commented
@lonvia The optional country codes are still supported, there are tests for it - I actually added some more, like "je JE5 0LA" will now be accepted as a legal post code "JE5 0LA" which was not the case previously. Obviously the preferred format is "JE5 0LA", but it is just to show that I did not touch the existing functionality.

2023-10-20 11:07 UTC, pawel-wroniszewski commented
@lonvia I think I see your concern - you meant I shouldn't have made the country settings stricter. I briefly checked the postcode format usage in OSM data and noticed that indeed, in most of in the countries affected in my first commit, the usage was mixed (a lot of postcodes not following the official format). As an exception, Latvia seemed to have all of the postcodes valid, while Andorra and  Cayman Islands had most of them valid. Nevertheless I don't want to mix two things in the PR and I reverted country settings change. I aligned unit tests with the current state of things.

2023-10-20 13:38 UTC, lonvia approved these changes
Indeed, that's what I meant. No need to be overly strict with OSM data here.

2023-10-23 08:35 UTC, merged